/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.SalesController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author adityauprety
 */
public class AdminPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
    * Creates new form AdminPanel
    * mainFrame - Reference to the main application frame for navigation
    */
    public AdminPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        loadUsersTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tblUsers = new javax.swing.JScrollPane();
        tblSalesList = new javax.swing.JTable();
        btnSortBySold = new javax.swing.JButton();
        btnSortByTotal = new javax.swing.JButton();
        btnSortByPending = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogoutAdmin = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Admin Page");

        tblSalesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Total Orders", "Pending Orders", "Items Sold"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSalesList.setShowGrid(true);
        tblUsers.setViewportView(tblSalesList);

        btnSortBySold.setBackground(new java.awt.Color(52, 152, 219));
        btnSortBySold.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortBySold.setForeground(new java.awt.Color(255, 255, 255));
        btnSortBySold.setText("Sort by Items Sold");
        btnSortBySold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortBySoldActionPerformed(evt);
            }
        });

        btnSortByTotal.setBackground(new java.awt.Color(46, 204, 113));
        btnSortByTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortByTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnSortByTotal.setText("Sort by Total Orders");
        btnSortByTotal.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btnSortByTotalMouseWheelMoved(evt);
            }
        });
        btnSortByTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByTotalActionPerformed(evt);
            }
        });

        btnSortByPending.setBackground(new java.awt.Color(243, 156, 18));
        btnSortByPending.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortByPending.setForeground(new java.awt.Color(255, 255, 255));
        btnSortByPending.setText("Sort by Pending");
        btnSortByPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByPendingActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnLogoutAdmin.setBackground(new java.awt.Color(108, 92, 231));
        btnLogoutAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogoutAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogoutAdmin.setText("Logout");
        btnLogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdminActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblUsers, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnSortByTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(btnSortByPending, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSortBySold, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnLogoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(530, 530, 530))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(tblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortByPending, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortByTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortBySold, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortBySoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortBySoldActionPerformed
        SalesController.bubbleSortByItemsSold();
        loadUsersTable();
        JOptionPane.showMessageDialog(this,
                "Sorted by Items Sold (Highest first)",
                "Sorted",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSortBySoldActionPerformed

    private void btnSortByTotalMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btnSortByTotalMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortByTotalMouseWheelMoved

    private void btnSortByTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByTotalActionPerformed
        SalesController.bubbleSortByTotalOrders();
        loadUsersTable();
        JOptionPane.showMessageDialog(this,
                "Sorted by Total Orders (Highest first)",
                "Sorted",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSortByTotalActionPerformed

    /**
    * Loads user data into the admin table.
    * Fetches all users (excluding admin) and displays their statistics.
    */
    private void loadUsersTable() {
        try {
            ArrayList<SalesController.User> users = SalesController.getAllUsers();

            String[] columns = {"Username", "Total Orders", "Pending Orders", "Items Sold"};
            DefaultTableModel model = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Non-editable
                }
            };

            for (SalesController.User user : users) {
                Object[] row = {
                    user.getUsername(),
                    user.getTotalOrders(),
                    user.getPendingOrders(),
                    user.getItemsSold()
                };
                model.addRow(row);
            }

            tblSalesList.setModel(model);

            // Auto-resize columns
            for (int i = 0; i < tblSalesList.getColumnCount(); i++) {
                tblSalesList.getColumnModel().getColumn(i).setPreferredWidth(150);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading users: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnSortByPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByPendingActionPerformed
        SalesController.bubbleSortByPendingOrders();
        loadUsersTable();
        JOptionPane.showMessageDialog(this,
                "Sorted by Pending Orders (Highest first)",
                "Sorted",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSortByPendingActionPerformed

    private void btnLogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAdminActionPerformed
        try {
            // Check if user is admin
            boolean isAdmin = controller.SalesController.isAdmin();
            String currentUsername = controller.SalesController.getCurrentUsername();

            if (!isAdmin) {
                controller.SalesController.logoutUser();
                mainFrame.showHome();
                return;
            }

            // Show confirmation dialog for admin logout
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Logout from admin account?\nUsername: " + currentUsername,
                    "Confirm Admin Logout",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                // Perform logout
                controller.SalesController.logoutUser();

                // Show success message
                JOptionPane.showMessageDialog(this,
                        "Admin logged out successfully!",
                        "Admin Logout",
                        JOptionPane.INFORMATION_MESSAGE);

                // Navigate to Home page
                mainFrame.showHome();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error during logout: " + e.getMessage(),
                    "Logout Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutAdminActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = tblSalesList.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a user to delete",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String username = tblSalesList.getValueAt(selectedRow, 0).toString();

        if (username.equals("admin")) {
            JOptionPane.showMessageDialog(this,
                    "Cannot delete admin account!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete user: " + username + "?\n"
                + "This will also delete all their sales records!",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = SalesController.deleteUser(username);

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "User deleted successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                loadUsersTable();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to delete user",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogoutAdmin;
    private javax.swing.JButton btnSortByPending;
    private javax.swing.JButton btnSortBySold;
    private javax.swing.JButton btnSortByTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblSalesList;
    private javax.swing.JScrollPane tblUsers;
    // End of variables declaration//GEN-END:variables
}
