/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import view.MainFrame;

/**
 *
 * @author adityauprety
 */
public class DashboardPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
    * Creates new form DashboardPanel
    * mainFrame - Reference to the main application frame for navigation
    */
    public DashboardPanel(MainFrame mainFrame) {  
        this.mainFrame = mainFrame;  
        initComponents();

        loadDashboardData();
        loadRecentSalesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddSales = new javax.swing.JButton();
        btnViewSales = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblSalesText = new javax.swing.JLabel();
        lblSoldValue = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnSearchSort = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTotalOrdersText = new javax.swing.JLabel();
        lblTotalOrdersValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPendingText = new javax.swing.JLabel();
        lblPendingValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecentSales = new javax.swing.JTable();
        btnLogoutDashboard = new javax.swing.JButton();

        btnAddSales.setBackground(new java.awt.Color(52, 152, 219));
        btnAddSales.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAddSales.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSales.setText("Add Sales");
        btnAddSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSalesActionPerformed(evt);
            }
        });

        btnViewSales.setBackground(new java.awt.Color(46, 204, 113));
        btnViewSales.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewSales.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSales.setText("View Sales");
        btnViewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalesActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblSalesText.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSalesText.setText("Total items");

        lblSoldValue.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblSoldValue.setForeground(new java.awt.Color(46, 204, 113));
        lblSoldValue.setText("0");

        jPanel6.setBackground(new java.awt.Color(46, 204, 113));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalesText)
                    .addComponent(lblSoldValue))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSalesText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoldValue)))
                .addGap(26, 26, 26))
        );

        btnSearchSort.setBackground(new java.awt.Color(108, 92, 231));
        btnSearchSort.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSearchSort.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSort.setText("Search / Sort");
        btnSearchSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSortActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTotalOrdersText.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotalOrdersText.setText("Total Orders");

        lblTotalOrdersValue.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTotalOrdersValue.setForeground(new java.awt.Color(52, 136, 219));
        lblTotalOrdersValue.setText("0");

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalOrdersValue)
                    .addComponent(lblTotalOrdersText))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalOrdersText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalOrdersValue)))
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("Dashboard");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Recenty added sales");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));

        lblPendingText.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPendingText.setText("Pending");

        lblPendingValue.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPendingValue.setForeground(new java.awt.Color(243, 156, 18));
        lblPendingValue.setText("0");

        jPanel5.setBackground(new java.awt.Color(243, 156, 18));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPendingText)
                    .addComponent(lblPendingValue))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPendingText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPendingValue)))
                .addGap(22, 22, 22))
        );

        tblRecentSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "", null, null, null},
                { new Integer(2), null, null, null, null},
                { new Integer(3), null, null, null, null},
                { new Integer(4), null, null, null, null},
                { new Integer(5), null, null, null, null},
                { new Integer(6), null, null, null, null},
                { new Integer(7), null, null, null, null},
                { new Integer(8), null, null, null, null},
                { new Integer(9), null, null, null, null},
                { new Integer(10), null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Item", "Quantity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRecentSales.setGridColor(new java.awt.Color(221, 221, 221));
        tblRecentSales.setRowHeight(28);
        tblRecentSales.setShowGrid(true);
        jScrollPane2.setViewportView(tblRecentSales);

        btnLogoutDashboard.setBackground(new java.awt.Color(255, 0, 0));
        btnLogoutDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogoutDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnLogoutDashboard.setText("Logout");
        btnLogoutDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addContainerGap(991, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(512, 512, 512))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddSales, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btnLogoutDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSales, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogoutDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSalesActionPerformed
        mainFrame.showAddSales();
    }//GEN-LAST:event_btnAddSalesActionPerformed

    private void btnViewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalesActionPerformed
        mainFrame.showSalesList();
    }//GEN-LAST:event_btnViewSalesActionPerformed

    private void btnSearchSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSortActionPerformed
        mainFrame.showSearchSort();
    }//GEN-LAST:event_btnSearchSortActionPerformed

    private void btnLogoutDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutDashboardActionPerformed
        try {
            // Check if user is already logged out
            String currentUsername = controller.SalesController.getCurrentUsername();

            if ("Guest".equals(currentUsername)) {
                // User is already logged out - go to home page silently
                mainFrame.showHome();
                return; 
            }

            // ONLY show confirmation dialog if user is actually logged in
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to logout?\nUsername: " + currentUsername,
                    "Confirm Logout",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                // Perform logout
                controller.SalesController.logoutUser();

                // Show success message
                JOptionPane.showMessageDialog(this,
                        "Logged out successfully!",
                        "Logout Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                // Navigate to Home page
                mainFrame.showHome();
            }
            // If user clicks NO, do nothing 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error during logout: " + e.getMessage(),
                    "Logout Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutDashboardActionPerformed

    /**
    * Loads dashboard statistics into display labels.
    * Shows different data for admin vs regular users.
    */
    public void loadDashboardData() {
        try {
            String[] stats;

            // Check if admin - admins see all stats
            if (controller.SalesController.isAdmin()) {
                stats = controller.SalesController.getDashboardStats();
            } else {
                // Regular users see only their stats
                stats = controller.SalesController.getDashboardStatsForCurrentUser();
            }

            if (stats != null && stats.length >= 3) {
                lblTotalOrdersValue.setText(stats[0]);
                lblPendingValue.setText(stats[1]);
                lblSoldValue.setText(stats[2]);
            } else {
                lblTotalOrdersValue.setText("0");
                lblPendingValue.setText("0");
                lblSoldValue.setText("0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading dashboard data: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            lblTotalOrdersValue.setText("0");
            lblPendingValue.setText("0");
            lblSoldValue.setText("0");
        }
    }

    /**
    * Loads recent sales into the dashboard table.
    * Shows up to 5 most recent sales based on user role.
    */
    public void loadRecentSalesTable() {
        try {
            // Get recent sales queue (max 5 items)
            controller.SalesController.RecentSalesQueue recentQueue = controller.SalesController.getRecentSalesQueue();

            // Create table model
            String[] columns = {"ID", "Name", "Item", "Quantity", "Status"};
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    switch (columnIndex) {
                        case 0:
                            return Integer.class;
                        case 1:
                            return String.class;
                        case 2:
                            return String.class;
                        case 3:
                            return Integer.class;
                        case 4:
                            return String.class;
                        default:
                            return Object.class;
                    }
                }
            };

            // Add recent sales to table (maximum 5)
            int count = 0;
            for (model.Sale sale : recentQueue.getItems()) {
                if (count >= 5) {
                    break;
                }
                Object[] row = {
                    sale.getId().replace("SALE", ""),
                    sale.getCustomerName(),
                    sale.getItem(),
                    sale.getQuantity(),
                    sale.getStatus()
                };
                model.addRow(row);
                count++;
            }

            // If no recent sales, show message in first row
            if (model.getRowCount() == 0) {
                Object[] row = {"No recent sales", "", "", "", ""};
                model.addRow(row);
            }

            // Set model to table
            tblRecentSales.setModel(model);

            for (int i = 0; i < tblRecentSales.getColumnCount(); i++) {
                tblRecentSales.getColumnModel().getColumn(i).setPreferredWidth(120);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading recent sales: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSales;
    private javax.swing.JButton btnLogoutDashboard;
    private javax.swing.JButton btnSearchSort;
    private javax.swing.JButton btnViewSales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPendingText;
    private javax.swing.JLabel lblPendingValue;
    private javax.swing.JLabel lblSalesText;
    private javax.swing.JLabel lblSoldValue;
    private javax.swing.JLabel lblTotalOrdersText;
    private javax.swing.JLabel lblTotalOrdersValue;
    private javax.swing.JTable tblRecentSales;
    // End of variables declaration//GEN-END:variables
}
