/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import controller.SalesController;
import model.Sale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adityauprety
 */
public class SalesListPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;  // ADD THIS LINE
    private java.util.ArrayList<model.Sale> currentDisplayList = null;  // CHANGE THIS LINE
    private String currentFilterType = "all";  // KEEP THIS

    /**
    * Creates new form SalesListPanel
    * mainFrame - Reference to the main application frame for navigation
    */
    public SalesListPanel(MainFrame mainFrame) {  
        this.mainFrame = mainFrame;  
        initComponents();
        loadSalesTable(); 
    }
    
    /**
    * Loads sales data into the table based on user role.
    * Admins see all sales, regular users see only their own sales.
    */
    private void loadSalesTable() {
        try {
            java.util.ArrayList<model.Sale> salesToDisplay;

            if (currentDisplayList != null && !currentDisplayList.isEmpty()) {
                salesToDisplay = currentDisplayList;
            } else {
                // Regular view - filter by user
                if (controller.SalesController.isAdmin()) {
                    // Admin sees all sales
                    salesToDisplay = controller.SalesController.getAllSales();
                } else {
                    // Regular user sees only their sales
                    salesToDisplay = controller.SalesController.getSalesForCurrentUser();
                }
            }

            // Create table model
            String[] columns = {"ID", "Name", "Item", "Price", "Quantity", "Total",
                "Status", "Payment", "Contact", "Date"};
            DefaultTableModel model = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make table read-only
                }
            };

            // Add sales to table
            for (model.Sale sale : salesToDisplay) {
                Object[] row = {
                    sale.getId(),
                    sale.getCustomerName(),
                    sale.getItem(),
                    String.format("$%.2f", sale.getPrice()),
                    sale.getQuantity(),
                    String.format("$%.2f", sale.getTotal()),
                    sale.getStatus(),
                    sale.getPaymentStatus(),
                    sale.getContactNumber(),
                    sale.getSaleDate().toString().substring(0, 16)
                };
                model.addRow(row);
            }

            // Set model to table
            tblSalesList.setModel(model);

            // Auto-resize columns
            for (int i = 0; i < tblSalesList.getColumnCount(); i++) {
                tblSalesList.getColumnModel().getColumn(i).setPreferredWidth(120);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading sales: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearchSort = new javax.swing.JButton();
        btnUndoDelete = new javax.swing.JButton();

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Sales List");

        tblSalesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Number", "Item", "Quantity", "Status", "Pricel", "Payment", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSalesList.setShowGrid(true);
        jScrollPane1.setViewportView(tblSalesList);

        btnBack.setBackground(new java.awt.Color(52, 152, 219));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(46, 204, 113));
        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                btnUpdateMouseWheelMoved(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnShowAll.setBackground(new java.awt.Color(243, 156, 18));
        btnShowAll.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnShowAll.setForeground(new java.awt.Color(255, 255, 255));
        btnShowAll.setText("Show all");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnSearchSort.setBackground(new java.awt.Color(108, 92, 231));
        btnSearchSort.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSearchSort.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSort.setText("Search / Sort");
        btnSearchSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSortActionPerformed(evt);
            }
        });

        btnUndoDelete.setBackground(new java.awt.Color(255, 153, 255));
        btnUndoDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUndoDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnUndoDelete.setText("↩");
        btnUndoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(530, 530, 530))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUndoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUndoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int selectedRow = tblSalesList.getSelectedRow();

            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please select a sale to delete",
                        "No Selection",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get the selected sale's ID
            String selectedId = tblSalesList.getValueAt(selectedRow, 0).toString();
            String customerName = tblSalesList.getValueAt(selectedRow, 1).toString();
            String item = tblSalesList.getValueAt(selectedRow, 2).toString();

            // Show confirmation dialog
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete this sale?\n\n"
                    + "ID: " + selectedId + "\n"
                    + "Customer: " + customerName + "\n"
                    + "Item: " + item + "\n\n"
                    + "This action cannot be undone!",
                    "Confirm Deletion",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                // Delete from DataStore
                boolean success = controller.SalesController.deleteSale(selectedId);

                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Sale deleted successfully!\n"
                            + "ID: " + selectedId + " has been removed.",
                            "Success",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Refresh the table
                    loadSalesTable();

                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Failed to delete sale.\n"
                            + "Sale ID " + selectedId + " not found.",
                            "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error deleting sale: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_btnUpdateMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseWheelMoved

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            int selectedRow = tblSalesList.getSelectedRow();

            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Please select a sale to update",
                        "No Selection",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get data from selected row
            String id = tblSalesList.getValueAt(selectedRow, 0).toString();
            String name = tblSalesList.getValueAt(selectedRow, 1).toString();
            String item = tblSalesList.getValueAt(selectedRow, 2).toString();
            String price = tblSalesList.getValueAt(selectedRow, 3).toString().replace("$", "");
            String quantity = tblSalesList.getValueAt(selectedRow, 4).toString();
            String status = tblSalesList.getValueAt(selectedRow, 6).toString();
            String payment = tblSalesList.getValueAt(selectedRow, 7).toString();
            String number = tblSalesList.getValueAt(selectedRow, 8).toString();

            // Open UpdateSalesPanel through MainFrame
            mainFrame.showUpdateSales(id, name, item, price, quantity, status, payment, number);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        currentDisplayList = null; 
        currentFilterType = "all";
        loadSalesTable(); // Show all sales

        javax.swing.JOptionPane.showMessageDialog(this,
                "Showing all sales",
                "Show All",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnSearchSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSortActionPerformed
        mainFrame.showSearchSort();
    }//GEN-LAST:event_btnSearchSortActionPerformed

    private void btnUndoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoDeleteActionPerformed
        Sale restoredSale = SalesController.undoDelete();

        if (restoredSale != null) {
            JOptionPane.showMessageDialog(this,
                    "Sale restored successfully!\n"
                    + "ID: " + restoredSale.getId() + "\n"
                    + "Customer: " + restoredSale.getCustomerName(),
                    "Undo Successful",
                    JOptionPane.INFORMATION_MESSAGE);

            loadSalesTable(); // Refresh the table
        } else {
            JOptionPane.showMessageDialog(this,
                    "No deleted sales to restore!",
                    "Undo Not Available",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUndoDeleteActionPerformed
    
    /**
    * Displays filtered sales results in the table.
    * filterType - Type of filter applied
    * sales - List of sales to display
    */
    public void displayFilteredSales(String filterType, java.util.ArrayList<model.Sale> sales) {
        this.currentFilterType = filterType;
        this.currentDisplayList = sales;
        loadSalesTable(); // Reload table with new data
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchSort;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUndoDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblSalesList;
    // End of variables declaration//GEN-END:variables
}
