/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import controller.SalesController;
import java.util.ArrayList;
import model.Sale;

/**
 *
 * @author adityauprety
 */
public class SearchSortPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
    * Creates new form SearchSortPanel
    * mainFrame - Reference to the main application frame for navigation
    */
    public SearchSortPanel(MainFrame mainFrame) {  // CHANGE CONSTRUCTOR
        this.mainFrame = mainFrame;  // ADD THIS LINE
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        txtSearchID = new javax.swing.JTextField();
        btnSearchStatus = new javax.swing.JButton();
        btnSearchID = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbSearchStatus = new javax.swing.JComboBox<>();
        btnSearchName = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbSearchPayment = new javax.swing.JComboBox<>();
        btnSearchPayment = new javax.swing.JButton();
        btnSortDate = new javax.swing.JButton();
        btnSortQuantity = new javax.swing.JButton();
        btnSortPrice = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnBack1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Search and Sort Sales Data");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Search by order ID");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Search by customer name");

        txtSearchName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtSearchID.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnSearchStatus.setBackground(new java.awt.Color(0, 0, 0));
        btnSearchStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchStatus.setText("Search");
        btnSearchStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStatusActionPerformed(evt);
            }
        });

        btnSearchID.setBackground(new java.awt.Color(0, 0, 0));
        btnSearchID.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchID.setText("Search");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Search by payment");

        cmbSearchStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Sold ", "Cancelled" }));

        btnSearchName.setText("Search");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Search by status");

        cmbSearchPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid ", " " }));

        btnSearchPayment.setText("Search");
        btnSearchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btnSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnSortDate.setBackground(new java.awt.Color(52, 152, 219));
        btnSortDate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortDate.setForeground(new java.awt.Color(255, 255, 255));
        btnSortDate.setText("Sort by date");
        btnSortDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortDateActionPerformed(evt);
            }
        });

        btnSortQuantity.setBackground(new java.awt.Color(255, 153, 255));
        btnSortQuantity.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortQuantity.setForeground(new java.awt.Color(255, 255, 255));
        btnSortQuantity.setText("Sort by Quantity");
        btnSortQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortQuantityActionPerformed(evt);
            }
        });

        btnSortPrice.setBackground(new java.awt.Color(243, 156, 18));
        btnSortPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortPrice.setForeground(new java.awt.Color(255, 255, 255));
        btnSortPrice.setText("Sort by price");
        btnSortPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortPriceActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnBack1.setBackground(new java.awt.Color(46, 204, 113));
        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSortPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSortDate, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSortQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(403, 403, 403))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(269, 351, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(218, 247, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 293, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortDate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 72, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 252, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStatusActionPerformed
        String searchStatus = cmbSearchStatus.getSelectedItem().toString().trim();

        if (searchStatus.isEmpty() || searchStatus.equals("Select")) {
            JOptionPane.showMessageDialog(this,
                    "Please select a status",
                    "Selection Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Sale> results;
        if (SalesController.isAdmin()) {
            results = new ArrayList<>();
            for (Sale sale : SalesController.getAllSales()) {
                if (sale.getStatus().equalsIgnoreCase(searchStatus)) {
                    results.add(sale);
                }
            }
        } else {
            results = SalesController.searchByStatusForCurrentUser(searchStatus);
        }

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No sales found with status: " + searchStatus,
                    "No Results",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(results, "Status: " + searchStatus);
    }//GEN-LAST:event_btnSearchStatusActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        String searchId = txtSearchID.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter an ID",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Sale foundSale;
        if (SalesController.isAdmin()) {
            foundSale = SalesController.binarySearchById(searchId);
        } else {
            foundSale = SalesController.binarySearchByIdForCurrentUser(searchId);
        }

        if (foundSale == null) {
            JOptionPane.showMessageDialog(this,
                    "No sale found with ID: " + searchId,
                    "Not Found",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        ArrayList<Sale> results = new ArrayList<>();
        results.add(foundSale);

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(results, "Binary Search Results for ID: " + searchId);
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        String searchName = txtSearchName.getText().trim();
        if (searchName.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a name",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Sale> results = SalesController.searchByCustomerName(searchName);

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No sales found for: " + searchName,
                    "No Results",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(results, "Search Results for: " + searchName);
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnSearchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPaymentActionPerformed
        String searchPayment = cmbSearchPayment.getSelectedItem().toString().trim();

        if (searchPayment.isEmpty() || searchPayment.equals("Select")) {
            JOptionPane.showMessageDialog(this,
                    "Please select a payment status",
                    "Selection Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Sale> results;
        if (SalesController.isAdmin()) {
            results = SalesController.searchByPaymentStatus(searchPayment);
        } else {
            results = SalesController.searchByPaymentStatusForCurrentUser(searchPayment);
        }

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No sales found with payment status: " + searchPayment,
                    "No Results",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(results, "Payment Status: " + searchPayment);
    }//GEN-LAST:event_btnSearchPaymentActionPerformed

    private void btnSortDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortDateActionPerformed
        ArrayList<Sale> sortedSales;

        if (SalesController.isAdmin()) {
            SalesController.sortByDate();
            sortedSales = SalesController.getAllSales();
        } else {
            sortedSales = SalesController.getSalesForCurrentUser();
            // Bubble sort by date (newest first)
            int n = sortedSales.size();
            for (int i = 0; i < n - 1; i++) {
                boolean swapped = false;
                for (int j = 0; j < n - i - 1; j++) {
                    if (sortedSales.get(j).getSaleDate().compareTo(sortedSales.get(j + 1).getSaleDate()) < 0) {
                        Sale temp = sortedSales.get(j);
                        sortedSales.set(j, sortedSales.get(j + 1));
                        sortedSales.set(j + 1, temp);
                        swapped = true;
                    }
                }
                if (!swapped) {
                    break;
                }
            }
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(sortedSales, "Sorted by Date (Newest First)");
    }//GEN-LAST:event_btnSortDateActionPerformed

    private void btnSortQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortQuantityActionPerformed
        if (SalesController.isAdmin()) {
            SalesController.bubbleSortByQuantity();
        }

        ArrayList<Sale> sortedSales;
        if (SalesController.isAdmin()) {
            sortedSales = SalesController.getAllSales();
        } else {
            sortedSales = SalesController.getSalesForCurrentUser();
            // sort user's sales by quantity
            int n = sortedSales.size();
            for (int i = 0; i < n - 1; i++) {
                boolean swapped = false;
                for (int j = 0; j < n - i - 1; j++) {
                    if (sortedSales.get(j).getQuantity() > sortedSales.get(j + 1).getQuantity()) {
                        Sale temp = sortedSales.get(j);
                        sortedSales.set(j, sortedSales.get(j + 1));
                        sortedSales.set(j + 1, temp);
                        swapped = true;
                    }
                }
                if (!swapped) {
                    break;
                }
            }
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(sortedSales, "Sorted by Quantity (Smallest to Largest)");
    }//GEN-LAST:event_btnSortQuantityActionPerformed

    private void btnSortPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortPriceActionPerformed
        ArrayList<Sale> sortedSales;

        if (SalesController.isAdmin()) {
            SalesController.sortByPrice();
            sortedSales = SalesController.getAllSales();
        } else {
            sortedSales = SalesController.getSalesForCurrentUser();
            // Bubble sort by price (low to high)
            int n = sortedSales.size();
            for (int i = 0; i < n - 1; i++) {
                boolean swapped = false;
                for (int j = 0; j < n - i - 1; j++) {
                    if (sortedSales.get(j).getPrice() > sortedSales.get(j + 1).getPrice()) {
                        Sale temp = sortedSales.get(j);
                        sortedSales.set(j, sortedSales.get(j + 1));
                        sortedSales.set(j + 1, temp);
                        swapped = true;
                    }
                }
                if (!swapped) {
                    break;
                }
            }
        }

        mainFrame.showSalesList();
        mainFrame.passSearchResultsToSalesList(sortedSales, "Sorted by Price (Low to High)");
    }//GEN-LAST:event_btnSortPriceActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        mainFrame.goBack();
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnSearchPayment;
    private javax.swing.JButton btnSearchStatus;
    private javax.swing.JButton btnSortDate;
    private javax.swing.JButton btnSortPrice;
    private javax.swing.JButton btnSortQuantity;
    private javax.swing.JComboBox<String> cmbSearchPayment;
    private javax.swing.JComboBox<String> cmbSearchStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtSearchID;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
